<?php

namespace denisok94\helper\yii2;

use yii\console\Controller;

/**
 * @author vitaliy-pashkov 
 */
class ConsoleController extends Controller
{
    public $json;
    public $params;

    public function options($actionID)
    {
        return ['json'];
    }

    public function beforeAction($action)
    {
        $this->params = json_decode($this->json, true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
