<?php

namespace denisok94\helper\yii2;

use yii\console\Controller;
use denisok94\helper\traits\ArrayHelper;

/**
 * ConsoleController
 * 
 * 
 * @example Пример:
 * ```php
 * // Вызвать `action` консольного контроллера:
 * H::exec('сontroller/action', [params]);
 * // Получить переданные параметры
 * $init = $this->params;
 * ```
 * 
 * @example Пример:
 * ```php
 * H::exec('my/test', ['test' => 'test']);
 * namespace app\commands;
 * class MyController extends ConsoleController
 * {
 *      public function actionTest()
 *      {
 *          $init = $this->params;
 * 		    $test = $this->params['test'];
 *      }
 * }
 * 
 * ```
 * @author vitaliy-pashkov 
 * 
 */
class ConsoleController extends Controller
{
    public $json;
    
    /**
     * @var array
     */
    public $params;

    public function options($actionID)
    {
        return ['json'];
    }

    public function beforeAction($action)
    {
        $this->params = ArrayHelper::toArray($this->json);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
